#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-1 -d 1 2 3 4 5
bspc monitor HDMI-2 -d 6 7 8 9 10

bspc config border_width        2
bspc config window_gap          10

bspc config focus_follows_pointer   true
bspc config single_monocle          true
bspc config automatic_scheme        alternate
bspc config presel_feedback         false

bspc config normal_border_color     "#44475a"
bspc config active_border_color     "#44475a"
bspc config focused_border_color    "#bd93f9"

bspc rule -a mpv                state=floating
bspc rule -a Nextcloud          state=floating  border=off  center=off
bspc rule -a lxqt-archiver      state=floating
bspc rule -a Pavucontrol        state=floating
bspc rule -a Blueman-manager    state=floating
bspc rule -a Zathura            state=tiled

wmname LG3D &
xsetroot -cursor_name left_ptr &
xcape -e "Super_L=Super_L|Escape" &
$HOME/.fehbg &
blueman-applet &
$HOME/.config/polybar/launch-bspwm.sh &
picom --experimental-backends &
unclutter &
dunst &
nextcloud &
$HOME/.config/redshift/launch.sh &
