#! /bin/sh

launch_bash_script() {
    pgrep -fx "bash $(which $1)" > /dev/null || $1 &
}

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-1 -d 1 2 3 4 5
bspc monitor HDMI-2 -d 6 7 8 9 10

bspc config border_width        2
bspc config window_gap          10

bspc config focus_follows_pointer   true
bspc config single_monocle          true
bspc config automatic_scheme        alternate
bspc config presel_feedback         false

bspc config normal_border_color     "#2E3440"
bspc config active_border_color     "#2E3440"
bspc config focused_border_color    "#88C0D0"

bspc rule -a Nextcloud          state=floating  border=off  center=off
bspc rule -a lxqt-archiver      state=floating
bspc rule -a Pavucontrol        state=floating
bspc rule -a Blueman-manager    state=floating
bspc rule -a Zathura            state=tiled

launch_bash_script tabbed-refresh

wmname LG3D &
xsetroot -cursor_name left_ptr &
xcape -e "Super_L=Super_L|Escape" &
$HOME/.fehbg &
$HOME/.config/polybar/launch-bspwm.sh &
picom --experimental-backends &
unclutter &
dunst &
nextcloud &
clipster -d &
$HOME/.config/redshift/launch.sh &
