#!/usr/bin/env bash

launch_bash_script() {
    args="${@:2}"
    [[ -n $args ]] && args=" $args"

    pkill -fx "bash $(which $1)$args"
    "$@" &
}

launch_xob() {
    fifo="/tmp/xob-$USER-$1"

    pkill -fx "xob -t 2000 -s $1"
    rm -f "$fifo"
    mkfifo "$fifo"
    tail -f "$fifo" | xob -t 2000 -s "$1" &
}

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-1 -d 1 2 3 4 5
bspc monitor HDMI-2 -d 6 7 8 9 10

bspc config border_width        2
bspc config window_gap          10

bspc config focus_follows_pointer   true
bspc config single_monocle          true
bspc config automatic_scheme        alternate
bspc config presel_feedback         false

bspc config normal_border_color     "#2E3440"
bspc config active_border_color     "#2E3440"
bspc config focused_border_color    "#88C0D0"

bspc rule -a Nextcloud:*:Nextcloud  state=floating  border=off  center=off
bspc rule -a lxqt-archiver          state=floating
bspc rule -a Pavucontrol            state=floating
bspc rule -a Zathura                state=tiled

launch_bash_script tabc refreshd
launch_bash_script feh-auto-reload

launch_xob volume

wmname LG3D &
xsetroot -cursor_name left_ptr &
xcape -e "Super_L=Super_L|Escape" &
$HOME/.fehbg &
$HOME/.config/polybar/launch-bspwm.sh &
picom &
unclutter &
dunst &
nextcloud &
clipster -d &
$HOME/.config/redshift/launch.sh &
mount-alberpi
